# Change these first
owner: teamcarma # Your GitHub organization or username, where this repository lives
repo: external-upptime # The name of this repository

sites:
  - name: GoCarma Website
    url: https://www.gocarma.com
  - name: TEST - GoCarma API Server
    url: $P_SITE_1
    method: POST
    headers:
    - "Authorization: Bearer $P_SECRET_SITE_1"
    - "Content-Type: application/json"
    body: '$P_SITE_BODY_1'
    icon: https://res.cloudinary.com/avego/image/upload/v1580811904/favicon_gynpkq.ico
  - name: GoCarma Support Site
    url: https://support.gocarma.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gocarma.com
  # baseUrl: /external-upptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://res.cloudinary.com/avego/image/upload/v1748354751/Carma_Logo_Long_Format_u9vhfv.png
  #name: GoCarma Upptime
  introTitle: "GoCarma services uptime"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/teamcarma/external-upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
